/* LeetCode 38- Count and Say

The sequence is generated by reading the previous term.

1
11        (one 1)
21        (two 1s)
1211      (one 2, one 1)
111221    (one 1, one 2, two 1s)
312211    (three 1s, two 2s, one 1)
Idea
Start with "1".
Repeat n-1 times:
Read the current string.
Count consecutive identical digits.
Append:
the count
then the digit.*/
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

int main() {

    int n = 5;

    char *ans = countAndSay(n);

    printf("%s\n", ans);

    free(ans);

    return 0;
}

char* countAndSay(int n) {

    char *current = (char*)malloc(5000);
    strcpy(current, "1");

    for (int i = 2; i <= n; i++) {

        char *next = (char*)malloc(5000);
        next[0] = '\0';

        int len = strlen(current);

        for (int j = 0; j < len;) {

            char digit = current[j];
            int count = 0;

            while (j < len && current[j] == digit) {
                count++;
                j++;
            }

            char temp[20];
            sprintf(temp, "%d%c", count, digit);

            strcat(next, temp);
        }

        free(current);
        current = next;
    }

    return current;
}